#!/bin/bash
#FONTPATH='/Library/Fonts/Andale Mono.ttf'
#FILTER_CHAIN="asplit=6[out1][a][b][c][d][e],\
#[e]showvolume=w=700:r=30:f=0.75:s=0[e1],\
#[a]showfreqs=mode=bar:cmode=separate:size=300x300:colors=magenta|yellow[aa],\
#[b]avectorscope=s=300x300:r=30:zoom=0[b1],\
#[c]showspectrum=s=400x600:slide=rscroll:mode=combined:color=rainbow:scale=lin:saturation=4[cc],\
#[d]avectorscope=s=700x256[d1],\
#[aa][b1]vstack[aabb],[aabb][cc]hstack[aabbcc],[e1][aabbcc][d1]vstack=3[z],\
#[z]drawtext=fontfile="${FONTPATH}": text='%{pts \\: hms}':x=460: y=50:fontcolor=white:fontsize=30:box=1:boxcolor=0x00000000@1[out0]"

#ffplay -window_title "Monitoring Channel(s): ${channel_layout}" -f lavfi "amovie=${1},${FILTER_CHAIN}"

FILTER_CHAIN="[aid1]asplit=5[ao][a][b][c][d],\
[a]showfreqs=mode=bar:cmode=separate:size=400x400:colors=magenta|yellow[a1],\
[b]avectorscope=s=400x400:r=30:zoom=0[b1],\
[c]showwaves=s=800x300:split_channels=1:r=30:mode=line[c1],\
[d]showspectrum=s=800x300:slide=rscroll:mode=combined:color=rainbow:scale=lin:saturation=4[d1],\
[a1][b1]hstack[ab],\
[ab][c1][d1]vstack=3[vo]"

mpv --force-window --keep-open=yes --geometry=800x898 "${1}" --lavfi-complex "${FILTER_CHAIN}"